"use client";

import { ICartItem, ICartState, Product, Variation } from "@/lib/models";
import useCart from "@/lib/components/Cart/useCart";
import { ReactElement } from "react";
import { CartIcon } from "@/lib/components/icons";

interface IProps {
  product: Product;
  variation: Variation;
  // Content must be rendered server side because it may call Square APIs, thus it cannot be generated by this component
  content: ReactElement;
  disabled: boolean;
}

export default function AddToCartButton({
  product,
  variation,
  content,
  disabled,
}: IProps) {
  const addItem = useCart((state: ICartState) => state.addItem);
  const item: ICartItem = {
    productId: product.id,
    variationId: variation.id,
    quantity: 1,
  };

  const NormalButton = () => (
    <a
      className="rounded-lg border cursor-pointer px-5 py-4 my-4 border-gray-300 transition-colors hover:border-gray-400 hover:bg-gray-100"
      onClick={() => addItem(item)}
    >
      <div className="flex items-center w-52">
        <div className="container w-7 h-7 mr-4">
          <CartIcon />
        </div>
        {content}
      </div>
    </a>
  );

  const DisabledButton = () => (
    <a
      className="group rounded-lg border cursor-not-allowed px-5 py-4 my-4 border-gray-300"
      onClick={() => addItem(item)}
    >
      <div className="flex items-center w-52">{content}</div>
    </a>
  );

  return <>{disabled ? <DisabledButton /> : <NormalButton />}</>;
}
