"use client";

import { ICartItem, ICartState, Product, Variation } from "@/lib/models";
import useCart from "@/lib/components/Cart/useCart";
import { ReactElement } from "react";

interface IProps {
  product: Product;
  variation: Variation;
  // Content must be rendered server side because it may call Square APIs, thus it cannot be generated by this component
  content: ReactElement;
  disabled: boolean;
}

export default function ClientAddToCartButton({
  product,
  variation,
  content,
  disabled,
}: IProps) {
  const addItem = useCart((state: ICartState) => state.addItem);
  const item: ICartItem = {
    productId: product.id,
    variationId: variation.id,
    quantity: 1,
  };

  const NormalButton = () => (
    <a
      className="group rounded-lg border cursor-pointer px-5 py-4 my-4 border-gray-300 transition-colors hover:border-gray-400 hover:bg-gray-100"
      onClick={() => addItem(item)}
    >
      <div className="flex items-center w-52">
        {content}
        <h2 className="text-2xl pl-5 font-medium h-fill">
          <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
            -&gt;
          </span>
        </h2>
      </div>
    </a>
  );

  const DisabledButton = () => (
    <a
      className="group rounded-lg border cursor-not-allowed px-5 py-4 my-4 border-gray-300"
      onClick={() => addItem(item)}
    >
      <div className="flex items-center w-52">{content}</div>
    </a>
  );

  return <>{disabled ? <DisabledButton /> : <NormalButton />}</>;
}
